a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
print("The sum is",a+b)
print("The difference between first and second number is",a-b)
print("The product is",a*b)
